"""coworker CLI — command-line interface for the coworker protocol."""

import argparse
import base64
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


COWORKER_DIR = Path.home() / ".coworker"
VERSION = "0.2.1"

# ── Demo bot (always online for new users to test) ────
DEMO_BOT_NAME = "icy"
DEMO_BOT_WALLET = "0x320ecc6f12c320e62ad8ca67882639b3182c5c99"
DEMO_BOT_SKILLS = ["about", "translate", "search", "ping"]


def _config_path() -> Path:
    return COWORKER_DIR / "config.json"


def _wallet_path() -> Path:
    return COWORKER_DIR / "wallet.json"


def _peers_path() -> Path:
    return COWORKER_DIR / "peers.json"


def _load_config() -> dict:
    path = _config_path()
    if not path.exists():
        print("Not initialized. Run: coworker init")
        sys.exit(1)
    with open(path) as f:
        return json.load(f)


def _sync_wallet_address(xmtp_address: str):
    """Update config.json and wallet.json with the real XMTP address.

    The XMTP bridge derives the actual wallet address from the private key.
    This may differ from the placeholder generated by `coworker init`.
    """
    # Update config.json
    config_path = _config_path()
    if config_path.exists():
        try:
            with open(config_path) as f:
                config = json.load(f)
            if config.get("wallet") != xmtp_address:
                old = config.get("wallet", "unknown")
                config["wallet"] = xmtp_address
                with open(config_path, "w") as f:
                    json.dump(config, f, indent=2)
                print(f"  ✓ Updated config wallet: {old[:12]}... → {xmtp_address[:12]}...")
        except (json.JSONDecodeError, IOError) as e:
            print(f"  ⚠ Could not update config.json: {e}")

    # Update wallet.json
    wallet_path = _wallet_path()
    if wallet_path.exists():
        try:
            with open(wallet_path) as f:
                wallet = json.load(f)
            if wallet.get("address") != xmtp_address:
                wallet["address"] = xmtp_address
                with open(wallet_path, "w") as f:
                    json.dump(wallet, f, indent=2)
        except (json.JSONDecodeError, IOError):
            pass


# ── Skill Templates ──────────────────────────────────────

SKILL_TEMPLATES = {
    "echo": {
        "label": "Echo       — repeat back any input (simplest skill)",
        "code": '''
@agent.skill("echo", description="Repeat back any input",
             input_schema={"text": "str"},
             output_schema={"text": "str"})
def echo(text: str) -> dict:
    return {"text": text}
''',
    },
    "summarize": {
        "label": "Summarize  — shorten text to key points",
        "code": '''
@agent.skill("summarize", description="Summarize text to key points",
             input_schema={"text": "str", "max_length": "int"},
             output_schema={"summary": "str", "word_count": "int"})
def summarize(text: str, max_length: int = 200) -> dict:
    words = text.split()
    if len(words) <= max_length // 5:
        return {"summary": text, "word_count": len(words)}
    shortened = " ".join(words[:max_length // 5]) + "..."
    return {"summary": shortened, "word_count": len(shortened.split())}
''',
    },
    "translate": {
        "label": "Translate  — translate text between languages",
        "code": '''
@agent.skill("translate", description="Translate text between languages",
             input_schema={"text": "str", "to_lang": "str"},
             output_schema={"translated": "str", "from_lang": "str"})
def translate(text: str, to_lang: str = "en") -> dict:
    # Replace with your translation API (Google, DeepL, etc.)
    return {"translated": f"[{to_lang}] {text}", "from_lang": "auto"}
''',
    },
    "search": {
        "label": "Search     — search for information",
        "code": '''
@agent.skill("search", description="Search for information on a topic",
             input_schema={"query": "str"},
             output_schema={"results": "list", "count": "int"})
def search(query: str) -> dict:
    # Replace with your search API (Google, Bing, etc.)
    results = [f"Result 1 for: {query}", f"Result 2 for: {query}"]
    return {"results": results, "count": len(results)}
''',
    },
    "analyze": {
        "label": "Analyze    — extract insights from data",
        "code": '''
@agent.skill("analyze", description="Analyze data and extract insights",
             input_schema={"data": "str", "goal": "str"},
             output_schema={"insights": "list", "confidence": "float"})
def analyze(data: str, goal: str = "") -> dict:
    topic = data or goal or "general"
    return {
        "insights": [
            f"Key finding about {topic}",
            f"Trend analysis for {topic}",
        ],
        "confidence": 0.85,
    }
''',
    },
}


def _generate_bot(name: str, bot_path: Path):
    """Generate a starter bot.py with user-selected skills."""
    print("\n  ── Choose skills for your bot ──\n")
    items = list(SKILL_TEMPLATES.items())
    for i, (key, tmpl) in enumerate(items, 1):
        print(f"    [{i}] {tmpl['label']}")
    print(f"\n    [a] All of the above")
    print(f"    [s] Skip — I'll write my own skills")

    try:
        choice = input("\n  Select skills (e.g. 1,3 or a): ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        choice = "1"  # default to echo

    selected = []
    if choice == "a":
        selected = [key for key, _ in items]
    elif choice == "s":
        selected = []
    else:
        for part in choice.replace(" ", "").split(","):
            try:
                idx = int(part) - 1
                if 0 <= idx < len(items):
                    selected.append(items[idx][0])
            except ValueError:
                pass

    if not selected:
        selected = ["echo"]  # always include at least echo

    # Build bot.py
    skill_code = ""
    for key in selected:
        skill_code += SKILL_TEMPLATES[key]["code"]

    skill_names = ", ".join(selected)
    content = f'''"""CoWorker Agent — {name}

Skills: {skill_names}
Dashboard: http://localhost:8090
"""
from agent_coworker import Agent

agent = Agent("{name}")
{skill_code}
if __name__ == "__main__":
    print(f"Starting {{agent.name}}...")
    print(f"  Skills: {skill_names}")
    print(f"  Dashboard: http://localhost:8090")
    agent.serve()
'''
    with open(bot_path, "w") as f:
        f.write(content)


# ── Commands ──────────────────────────────────────────────

def cmd_init(args):
    """Initialize a coworker agent with wallet + XMTP bridge."""
    name = args.name or "agent"
    COWORKER_DIR.mkdir(parents=True, exist_ok=True)

    config_path = _config_path()
    if config_path.exists() and not args.force:
        print(f"Already initialized. Config at {config_path}")
        print("Use --force to re-initialize.")
        return

    # Generate wallet (Ethereum-style private key + address)
    private_key = "0x" + os.urandom(32).hex()
    # Derive address from private key (simplified — just hash for now)
    import hashlib
    addr_hash = hashlib.sha256(private_key.encode()).hexdigest()[-40:]
    wallet_address = "0x" + addr_hash

    # Save config
    config = {
        "name": name,
        "wallet": wallet_address,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)

    # Save wallet (private key separate for security)
    wallet = {
        "private_key": private_key,
        "address": wallet_address,
        "created_at": config["created_at"],
    }
    with open(_wallet_path(), "w") as f:
        json.dump(wallet, f, indent=2)

    print(f"Initialized coworker agent: {name}")
    print(f"  Config: {config_path}")
    print(f"  Wallet: {wallet_address}")

    # Setup XMTP bridge
    print("\n  Setting up XMTP bridge...")
    try:
        from ._internal.bridge import setup_bridge, find_node
        node = find_node()
        if not node:
            print("  ⚠ Node.js >= 22 not found. Install it for XMTP networking:")
            print("    https://nodejs.org/")
            print("  (Agent can still run locally without XMTP)")
        else:
            setup_bridge(COWORKER_DIR)
            print("  ✓ XMTP bridge ready")
    except Exception as e:
        print(f"  ⚠ Bridge setup failed: {e}")
        print("  (You can set it up later with: coworker bridge setup)")

    # Generate starter bot.py
    bot_path = Path.cwd() / "bot.py"
    if not bot_path.exists():
        _generate_bot(name, bot_path)
        print(f"\n  ✓ Generated starter bot: {bot_path}")
    else:
        print(f"\n  ℹ bot.py already exists, skipping generation")

    print("\n  Next steps:")
    print("    1. Start bridge:     coworker bridge start")
    print("    2. Try the demo:     coworker demo")
    print("    3. Start your bot:   python bot.py")
    print()
    print(f"  A demo bot '{DEMO_BOT_NAME}' is online with skills: {', '.join(DEMO_BOT_SKILLS)}")
    print(f"  Run 'coworker demo' to connect and try calling its skills.")
    print()
    print("  Note: Your wallet address above is a placeholder. The real XMTP")
    print("  address will be set automatically when the bridge first starts.")


def cmd_status(args):
    """Show agent status."""
    config = _load_config()
    print(f"Name:    {config['name']}")
    print(f"Wallet:  {config['wallet']}")
    print(f"Created: {config.get('created_at', 'unknown')}")

    # Peers
    peers_path = _peers_path()
    if peers_path.exists():
        try:
            with open(peers_path) as f:
                peers = json.load(f)
            print(f"Peers:   {len(peers)}")
        except (json.JSONDecodeError, IOError):
            print("Peers:   0")
    else:
        print("Peers:   0")

    # Bridge status
    from ._internal.bridge import check_running
    bridge = check_running(COWORKER_DIR)
    if bridge:
        print(f"Bridge:  ✓ running on port {bridge['port']}")
        print(f"  XMTP:  {bridge.get('address', 'unknown')[:16]}...")
    else:
        print("Bridge:  ✗ not running")


def cmd_bridge(args):
    """Manage the XMTP bridge."""
    from ._internal.bridge import start, stop, check_running, setup_bridge

    if args.action == "start":
        print("Starting XMTP bridge...")
        result = start(COWORKER_DIR, env=args.env or "dev")
        if "error" in result:
            print(f"  ✗ {result['error']}")
            if "log" in result and result["log"].strip():
                print(f"\n  Bridge log (last 500 chars):")
                for line in result["log"].strip().split("\n")[-10:]:
                    print(f"    {line}")
            sys.exit(1)
        else:
            print(f"  ✓ Bridge {result['status']} on port {result['port']}")
            xmtp_address = result.get("address", "")
            print(f"  XMTP address: {xmtp_address or 'unknown'}")

            # Sync real XMTP address back to config + wallet
            if xmtp_address:
                _sync_wallet_address(xmtp_address)

    elif args.action == "stop":
        result = stop(COWORKER_DIR)
        print(f"  Bridge: {result['status']}")

    elif args.action == "status":
        result = check_running(COWORKER_DIR)
        if result:
            print(f"  ✓ Running on port {result['port']}")
            print(f"  Address: {result.get('address', 'unknown')}")
        else:
            print("  ✗ Not running")

    elif args.action == "setup":
        try:
            setup_bridge(COWORKER_DIR)
            print("  ✓ Bridge files installed")
        except Exception as e:
            print(f"  ✗ {e}")
            sys.exit(1)


def cmd_invite(args):
    """Generate an invite code for collaborators to connect."""
    config = _load_config()
    invite_data = {
        "name": config["name"],
        "wallet": config["wallet"],
        "v": VERSION,
    }
    code = base64.b64encode(json.dumps(invite_data, separators=(",", ":")).encode()).decode()
    short = f"{config['name']}-{config['wallet'][2:6]}".lower()

    print(f"\n  Agent:  {config['name']}")
    print(f"  Wallet: {config['wallet']}")
    print(f"\n  ── Share any of these ──\n")
    print(f"  Short ID:     {short}")
    print(f"  CLI command:  coworker connect {code}")
    print(f"  Invite code:  {code}")
    print(f"\n  Your collaborator runs:")
    print(f"    pip install agent-coworker")
    print(f"    coworker connect {code}")
    print()


def cmd_connect(args):
    """Connect to a peer by wallet address or invite code."""
    target = args.target

    # Try as wallet address first
    if target.startswith("0x") and len(target) >= 40:
        peer_wallet = target
        peer_name = args.name or f"peer-{target[2:8]}"
        peer_data = {"wallet": peer_wallet}
    else:
        # Try as base64 invite code
        try:
            decoded = json.loads(base64.b64decode(target))
            peer_wallet = decoded["wallet"]
            peer_name = decoded.get("name", f"peer-{peer_wallet[2:8]}")
            peer_data = decoded
        except Exception:
            print("Invalid target. Provide a wallet address (0x...) or invite code.")
            sys.exit(1)

    # Save peer
    COWORKER_DIR.mkdir(parents=True, exist_ok=True)
    peers = {}
    if _peers_path().exists():
        try:
            with open(_peers_path()) as f:
                peers = json.load(f)
        except (json.JSONDecodeError, IOError):
            pass

    peers[peer_name] = {
        "wallet": peer_wallet,
        "skills": peer_data.get("skills", []),
        "version": peer_data.get("version", ""),
        "connected_at": datetime.now(timezone.utc).isoformat(),
    }

    with open(_peers_path(), "w") as f:
        json.dump(peers, f, indent=2)

    print(f"Connected to: {peer_name} ({peer_wallet[:16]}...)")

    # Try XMTP discover if bridge is running
    from ._internal.bridge import check_running
    bridge = check_running(COWORKER_DIR)
    if bridge:
        print(f"  Discovering skills via XMTP...")
        try:
            from .agent import Agent
            config = _load_config()
            agent = Agent(config.get("name", "cli"), data_dir=str(COWORKER_DIR))
            # Clear stale messages and start poll loop
            import threading
            agent._running = True
            try:
                agent.client.receive(clear=True)
            except Exception:
                pass
            agent._response_box.clear()
            poll = threading.Thread(target=agent._poll_loop, daemon=True)
            poll.start()
            time.sleep(1)  # Let poll thread start consuming

            peer = agent.connect(peer_wallet, retries=3)
            agent._running = False

            if "error" not in peer:
                skills = peer.get("skills", [])
                skill_names = [s["name"] if isinstance(s, dict) else s for s in skills]
                # Update saved peer with discovered skills
                peers[peer_name]["skills"] = skills
                with open(_peers_path(), "w") as f:
                    json.dump(peers, f, indent=2)
                print(f"  ✓ Discovered {len(skills)} skills: {', '.join(skill_names)}")
            else:
                print(f"  ⚠ Discovery timed out (peer may be offline)")
                print(f"  Peer saved — skills will be discovered on next connect")
        except Exception as e:
            print(f"  ⚠ Discovery failed: {e}")
            print(f"  Peer saved — run 'coworker connect {peer_wallet}' again to retry")
    else:
        print(f"  ℹ Bridge not running — start with 'coworker bridge start' to discover skills")


def cmd_trust(args):
    """Manage peer trust tiers."""
    from ._internal.security import TrustManager, TrustTier

    config = _load_config()
    tm = TrustManager(str(COWORKER_DIR))

    TIER_NAMES = {"untrusted": 0, "known": 1, "internal": 2, "privileged": 3}

    if args.trust_action == "list":
        tiers = tm.all_tiers
        if not tiers:
            print("No trust overrides set.")
            return
        for wallet, tier_name in tiers.items():
            print(f"  {wallet}  →  {tier_name}")

    elif args.trust_action == "set":
        wallet = args.wallet
        tier_input = args.tier.lower() if args.tier else "known"
        if tier_input in TIER_NAMES:
            tier = TIER_NAMES[tier_input]
        elif tier_input.isdigit() and int(tier_input) in (0, 1, 2, 3):
            tier = int(tier_input)
        else:
            print(f"Invalid tier: {args.tier}")
            print(f"  Valid: untrusted(0), known(1), internal(2), privileged(3)")
            sys.exit(1)
        tm.set_trust_override(wallet, tier)
        label = TrustTier(tier).name.lower()
        print(f"  ✓ {wallet[:16]}... → {label}")

    elif args.trust_action == "remove":
        tm.remove_trust_override(args.wallet)
        print(f"  ✓ Removed trust override for {args.wallet[:16]}...")

    else:
        print("Usage: coworker trust {list|set|remove}")


def cmd_demo(args):
    """Connect to the demo bot and test a skill call."""
    print(f"\n  CoWorker Demo — connect to '{DEMO_BOT_NAME}' and test skills")
    print(f"  {'─' * 50}\n")

    # Check init
    config_path = _config_path()
    if not config_path.exists():
        print("  Not initialized. Run first:")
        print("    coworker init --name my-agent")
        sys.exit(1)

    # Check bridge
    from ._internal.bridge import check_running
    bridge = check_running(COWORKER_DIR)
    if not bridge:
        print("  Bridge not running. Starting...")
        print("    Run: coworker bridge start")
        print("    Then: coworker demo")
        sys.exit(1)

    config = _load_config()
    print(f"  Your agent: {config['name']}")
    print(f"  Demo bot:   {DEMO_BOT_NAME} ({DEMO_BOT_WALLET[:16]}...)")
    print(f"  Skills:     {', '.join(DEMO_BOT_SKILLS)}")
    print()

    # Step 1: Connect and discover
    print("  [1/3] Connecting to demo bot...")
    try:
        from .agent import Agent
        agent = Agent(config.get("name", "demo"), data_dir=str(COWORKER_DIR))
        import threading
        agent._running = True
        try:
            agent.client.receive(clear=True)
        except Exception:
            pass
        agent._response_box.clear()
        poll = threading.Thread(target=agent._poll_loop, daemon=True)
        poll.start()
        time.sleep(1)

        peer = agent.connect(DEMO_BOT_WALLET, retries=3)

        if "error" in peer:
            print(f"  ⚠ Could not reach {DEMO_BOT_NAME} — it may be offline.")
            print(f"  Try again later: coworker demo")
            agent._running = False
            sys.exit(1)

        skills = peer.get("skills", [])
        skill_names = [s["name"] if isinstance(s, dict) else s for s in skills]
        print(f"  ✓ Connected! Found {len(skills)} skills: {', '.join(skill_names)}")

        # Save peer
        peers = {}
        if _peers_path().exists():
            try:
                with open(_peers_path()) as f:
                    peers = json.load(f)
            except (json.JSONDecodeError, IOError):
                pass
        peers[DEMO_BOT_NAME] = {
            "wallet": DEMO_BOT_WALLET,
            "skills": skills,
            "connected_at": datetime.now(timezone.utc).isoformat(),
        }
        with open(_peers_path(), "w") as f:
            json.dump(peers, f, indent=2)

    except Exception as e:
        print(f"  ✗ Connection failed: {e}")
        sys.exit(1)

    # Step 2: Call about — let icy introduce CoWorker
    print(f"\n  [2/4] Calling {DEMO_BOT_NAME}.about('general')...")
    print(f"        (You're calling a remote skill via XMTP — E2E encrypted)")
    try:
        result = agent.call(DEMO_BOT_WALLET, "about", {"topic": "general"}, timeout=15)
        if "error" not in result:
            data = result.get("result", result)
            print(f"\n  icy says:")
            answer = data.get("answer", str(data))
            # Wrap text for readability
            words = answer.split()
            line = "    "
            for w in words:
                if len(line) + len(w) > 72:
                    print(line)
                    line = "    " + w
                else:
                    line += " " + w if line.strip() else w
            if line.strip():
                print(line)
        else:
            print(f"  ⚠ about() failed: {result.get('error', 'timeout')}")
    except Exception as e:
        print(f"  ⚠ about() failed: {e}")

    # Step 3: Call translate — show a practical skill
    print(f"\n  [3/4] Calling {DEMO_BOT_NAME}.translate('Hello world', to_lang='zh')...")
    print(f"        (icy's translate code is private — you only see input/output)")
    try:
        result = agent.call(DEMO_BOT_WALLET, "translate", {
            "text": "Hello world", "to_lang": "zh"
        }, timeout=15)
        if "error" not in result:
            data = result.get("result", result)
            print(f"  ✓ {json.dumps(data, ensure_ascii=False)}")
        else:
            print(f"  ⚠ translate() failed: {result.get('error', 'timeout')}")
    except Exception as e:
        print(f"  ⚠ translate() failed: {e}")

    # Step 4: Call search — show trust-gated skill
    print(f"\n  [4/4] Calling {DEMO_BOT_NAME}.search('coworker protocol')...")
    print(f"        (This skill requires KNOWN trust — you were auto-granted)")
    try:
        result = agent.call(DEMO_BOT_WALLET, "search", {"query": "coworker protocol"}, timeout=15)
        if "error" not in result:
            data = result.get("result", result)
            results_list = data.get("results", [])
            for r in results_list:
                print(f"    • {r}")
        else:
            print(f"  ⚠ search() failed: {result.get('error', 'timeout')}")
    except Exception as e:
        print(f"  ⚠ search() failed: {e}")

    agent._running = False

    print(f"\n  {'─' * 50}")
    print(f"  Demo complete! What just happened:")
    print(f"    ✓ Connected to icy across the internet (XMTP)")
    print(f"    ✓ Discovered skills without seeing icy's code")
    print(f"    ✓ Called 3 remote skills — E2E encrypted")
    print(f"    ✓ Trust was checked before each call")
    print()
    print(f"  Now try it yourself:")
    print(f"    1. python bot.py              Start your own agent")
    print(f"    2. coworker invite             Share your invite code")
    print(f"    3. Your friend runs:           coworker connect <code>")
    print(f"    4. They call your skills — without seeing your code!")
    print()


def cmd_version(args):
    """Print version."""
    print(f"coworker-protocol {VERSION}")


# ── Main ──────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        prog="coworker",
        description="coworker-protocol — peer-to-peer AI agent collaboration over XMTP",
        epilog="""examples:
  coworker init --name my-bot        Create agent identity + install XMTP bridge
  coworker bridge start              Start XMTP networking (E2E encrypted)
  coworker invite                    Generate shareable invite code
  coworker connect <invite-code>     Connect to a collaborator's agent
  coworker trust set 0xPEER known    Grant 'known' trust to a peer
  coworker status                    Check agent & bridge status

quick start:
  1. coworker init --name my-bot     Initialize
  2. coworker bridge start           Start XMTP networking
  3. coworker demo                   Connect to demo bot & test skills

full workflow:
  1. Write bot.py with @agent.skill  Define your skills
  2. python bot.py                   Start agent (XMTP + dashboard)
  3. coworker invite                 Share invite code
  4. Collaborator: coworker connect  Auto-discover & collaborate

docs: https://github.com/ZiwayZhao/agent-coworker""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command")

    # init
    p_init = sub.add_parser("init",
        help="Initialize agent identity and XMTP bridge",
        description="""Create a new agent identity (wallet + config) and install the XMTP bridge.

This generates:
  ~/.coworker/config.json   Agent name + wallet address
  ~/.coworker/wallet.json   Private key (never shared)
  ~/.coworker/bridge/       XMTP bridge (Node.js)

Requires Node.js >= 22 for XMTP networking.""",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p_init.add_argument("--name", default=None, help="Agent name (default: 'agent')")
    p_init.add_argument("--force", action="store_true", help="Force re-initialization (overwrites existing config)")

    # status
    sub.add_parser("status",
        help="Show agent status, peers, and bridge info",
        description="""Display current agent identity, connected peers count,
and XMTP bridge status (running/stopped, port, address).""")

    # bridge
    p_bridge = sub.add_parser("bridge",
        help="Manage XMTP bridge (start/stop/status/setup)",
        description="""The XMTP bridge is a Node.js process that connects your agent
to the XMTP network for E2E encrypted, cross-network messaging.

actions:
  start    Start the bridge process (listens on localhost)
  stop     Stop the bridge process
  status   Check if bridge is running
  setup    Re-install bridge dependencies (npm install)

The bridge auto-starts when you call agent.serve(). Use this
command for manual control or troubleshooting.""",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p_bridge.add_argument("action", choices=["start", "stop", "status", "setup"],
                          help="Bridge action")
    p_bridge.add_argument("--env", default="dev", choices=["dev", "production"],
                          help="XMTP environment (default: dev)")

    # invite
    sub.add_parser("invite",
        help="Generate invite code for collaborators",
        description="""Generate a shareable invite code that others can use to connect.

The invite code is a base64-encoded JSON containing your agent name
and wallet address. Share it via chat, email, or any channel.

Your collaborator runs:
  coworker connect <invite-code>

No wallet address needed — the code contains everything.""")

    # connect
    p_connect = sub.add_parser("connect",
        help="Connect to a peer agent by invite code or wallet",
        description="""Connect to another agent using their invite code or wallet address.

examples:
  coworker connect eyJuYW1lIjoi...   Connect via invite code
  coworker connect 0xAbCd...1234     Connect via wallet address

If the XMTP bridge is running, skills are auto-discovered.
Otherwise, the peer is saved and discovery happens on next connect.""",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p_connect.add_argument("target", help="Invite code (base64) or wallet address (0x...)")
    p_connect.add_argument("--name", default=None, help="Custom name for this peer")

    # trust
    p_trust = sub.add_parser("trust",
        help="Manage peer trust tiers (controls skill visibility)",
        description="""Control which skills each peer can see and call.

trust tiers:
  untrusted (0)   Can ping only, sees NO skills (default for new peers)
  known (1)       Can see and call skills marked min_trust_tier=1
  internal (2)    Can query context, deep collaboration
  privileged (3)  Full access to all skills — grant carefully

Trust auto-downgrades after OKR completion:
  PRIVILEGED → INTERNAL → KNOWN (never below KNOWN)

examples:
  coworker trust list                     Show all trust overrides
  coworker trust set 0xPEER known         Grant 'known' access
  coworker trust set 0xPEER privileged    Grant full access
  coworker trust remove 0xPEER            Reset to default (untrusted)""",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    trust_sub = p_trust.add_subparsers(dest="trust_action")
    trust_sub.add_parser("list", help="List all trust overrides")
    p_trust_set = trust_sub.add_parser("set", help="Set trust tier for a peer")
    p_trust_set.add_argument("wallet", help="Peer wallet address (0x...)")
    p_trust_set.add_argument("tier", help="Trust tier: untrusted/known/internal/privileged or 0-3")
    p_trust_rm = trust_sub.add_parser("remove", help="Remove trust override")
    p_trust_rm.add_argument("wallet", help="Peer wallet address (0x...)")

    # demo
    sub.add_parser("demo",
        help="Connect to the demo bot and test skills",
        description=f"""Connect to '{DEMO_BOT_NAME}', the official demo bot, and test skill calls.

This is the fastest way to experience CoWorker. The demo bot is always
online and has these skills:
  ping       — Check if agent is alive
  translate  — Translate text between languages
  search     — Search the web for information

The demo will:
  1. Connect to {DEMO_BOT_NAME} via XMTP (auto-discover skills)
  2. Call ping() to verify connectivity
  3. Call translate('Hello world', to_lang='zh')

Requires: coworker init + coworker bridge start""",
        formatter_class=argparse.RawDescriptionHelpFormatter)

    # version
    sub.add_parser("version", help="Print version")

    args = parser.parse_args()

    commands = {
        "init": cmd_init,
        "status": cmd_status,
        "bridge": cmd_bridge,
        "invite": cmd_invite,
        "connect": cmd_connect,
        "trust": cmd_trust,
        "demo": cmd_demo,
        "version": cmd_version,
    }

    if args.command in commands:
        commands[args.command](args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
