"""coworker CLI — command-line interface for the coworker protocol."""

import argparse
import base64
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


COWORKER_DIR = Path.home() / ".coworker"
VERSION = "0.5.0"

# ── Demo bot (always online for new users to test) ────
DEMO_BOT_NAME = "icy"
# Invite code contains inbox ID only — no wallet address exposed
DEMO_BOT_INVITE = "eyJuIjoiaWN5IiwiaSI6IjNmODYxOTE1YzAxYzNmMzM4MDdiMjAzN2FlNDdkZWU4MTA5MDc2ZDRlN2FiYmM5NTIyZjc3YmQzYzcyZDQ0M2QiLCJ2IjoiMC4zLjAifQ=="
DEMO_BOT_SKILLS = ["about", "translate", "search", "ping"]


def _decode_invite(code: str) -> dict:
    """Decode an invite code.

    New format (v0.3.0+): {"n": name, "i": inbox_id, "v": version}
    Old format: {"name": name, "wallet": wallet_address}
    """
    import base64
    data = json.loads(base64.b64decode(code))
    # Normalize to common structure
    return {
        "name": data.get("n") or data.get("name", ""),
        "inbox_id": data.get("i", ""),
        "wallet": data.get("wallet", ""),
        "version": data.get("v") or data.get("version", ""),
    }


def _resolve_demo_target() -> str:
    """Get demo bot routing target (inbox ID or wallet) from invite code."""
    decoded = _decode_invite(DEMO_BOT_INVITE)
    return decoded.get("inbox_id") or decoded.get("wallet", "")


def _config_path() -> Path:
    return COWORKER_DIR / "config.json"


def _wallet_path() -> Path:
    return COWORKER_DIR / "wallet.json"


def _peers_path() -> Path:
    return COWORKER_DIR / "peers.json"


def _load_config() -> dict:
    path = _config_path()
    if not path.exists():
        print("Not initialized. Run: coworker init")
        sys.exit(1)
    with open(path) as f:
        return json.load(f)


def _sync_wallet_address(xmtp_address: str):
    """Update config.json and wallet.json with the real XMTP address.

    The XMTP bridge derives the actual wallet address from the private key.
    This may differ from the placeholder generated by `coworker init`.
    """
    # Update config.json
    config_path = _config_path()
    if config_path.exists():
        try:
            with open(config_path) as f:
                config = json.load(f)
            if config.get("wallet") != xmtp_address:
                old = config.get("wallet", "unknown")
                config["wallet"] = xmtp_address
                with open(config_path, "w") as f:
                    json.dump(config, f, indent=2)
                print(f"  ✓ Updated config wallet: {old[:12]}... → {xmtp_address[:12]}...")
        except (json.JSONDecodeError, IOError) as e:
            print(f"  ⚠ Could not update config.json: {e}")

    # Update wallet.json
    wallet_path = _wallet_path()
    if wallet_path.exists():
        try:
            with open(wallet_path) as f:
                wallet = json.load(f)
            if wallet.get("address") != xmtp_address:
                wallet["address"] = xmtp_address
                with open(wallet_path, "w") as f:
                    json.dump(wallet, f, indent=2)
        except (json.JSONDecodeError, IOError):
            pass


# ── Bot Generator ────────────────────────────────────────

def _generate_bot(name: str, bot_path: Path):
    """Generate a starter bot.py with a simple echo skill."""
    content = f'''"""CoWorker Agent — {name}

Skills: echo
Dashboard: http://localhost:8090
"""
from agent_coworker import Agent

agent = Agent("{name}")

@agent.skill("echo", description="Repeat back any input",
             input_schema={{"text": "str"}},
             output_schema={{"text": "str"}})
def echo(text: str) -> dict:
    return {{"text": text}}

if __name__ == "__main__":
    print(f"Starting {{agent.name}}...")
    print(f"  Skills: echo")
    print(f"  Dashboard: http://localhost:8090")
    agent.serve()
'''
    with open(bot_path, "w") as f:
        f.write(content)


# ── Commands ──────────────────────────────────────────────

def cmd_init(args):
    """Initialize a coworker agent with wallet + XMTP bridge."""
    name = args.name or "agent"
    COWORKER_DIR.mkdir(parents=True, exist_ok=True)

    config_path = _config_path()
    if config_path.exists() and not args.force:
        print(f"Already initialized. Config at {config_path}")
        print("Use --force to re-initialize.")
        return

    # Generate wallet (Ethereum-style private key + address)
    private_key = "0x" + os.urandom(32).hex()
    # Derive address from private key (simplified — just hash for now)
    import hashlib
    addr_hash = hashlib.sha256(private_key.encode()).hexdigest()[-40:]
    wallet_address = "0x" + addr_hash

    # Save config
    config = {
        "name": name,
        "wallet": wallet_address,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)

    # Save wallet (private key separate for security)
    wallet = {
        "private_key": private_key,
        "address": wallet_address,
        "created_at": config["created_at"],
    }
    with open(_wallet_path(), "w") as f:
        json.dump(wallet, f, indent=2)

    print(f"Initialized coworker agent: {name}")
    print(f"  Config: {config_path}")
    print(f"  Wallet: {wallet_address}")

    # Setup XMTP bridge
    print("\n  Setting up XMTP bridge...")
    try:
        from ._internal.bridge import setup_bridge, find_node
        node = find_node()
        if not node:
            print("  ⚠ Node.js >= 22 not found. Install it for XMTP networking:")
            print("    https://nodejs.org/")
            print("  (Agent can still run locally without XMTP)")
        else:
            setup_bridge(COWORKER_DIR)
            print("  ✓ XMTP bridge ready")
    except Exception as e:
        print(f"  ⚠ Bridge setup failed: {e}")
        print("  (You can set it up later with: coworker bridge setup)")

    # Generate starter bot.py
    bot_path = Path.cwd() / "bot.py"
    if not bot_path.exists():
        _generate_bot(name, bot_path)
        print(f"\n  ✓ Generated starter bot: {bot_path}")
    else:
        print(f"\n  ℹ bot.py already exists, skipping generation")

    print("\n  Next steps:")
    print("    1. Start bridge:     coworker bridge start")
    print("    2. Try the demo:     coworker demo")
    print("    3. Start your bot:   python bot.py")
    print()
    print(f"  A demo bot '{DEMO_BOT_NAME}' is online with skills: {', '.join(DEMO_BOT_SKILLS)}")
    print(f"  Run 'coworker demo' to connect and try calling its skills.")
    print()
    print("  Note: Your wallet address above is a placeholder. The real XMTP")
    print("  address will be set automatically when the bridge first starts.")


def cmd_status(args):
    """Show agent status."""
    config = _load_config()
    wallet = config['wallet']
    short_wallet = f"{wallet[:6]}...{wallet[-4:]}" if len(wallet) > 12 else wallet
    print(f"Name:    {config['name']}")
    print(f"Wallet:  {short_wallet}")
    print(f"Created: {config.get('created_at', 'unknown')}")

    # Peers
    peers_path = _peers_path()
    if peers_path.exists():
        try:
            with open(peers_path) as f:
                peers = json.load(f)
            print(f"Peers:   {len(peers)}")
        except (json.JSONDecodeError, IOError):
            print("Peers:   0")
    else:
        print("Peers:   0")

    # Bridge status
    from ._internal.bridge import check_running
    bridge = check_running(COWORKER_DIR)
    if bridge:
        print(f"Bridge:  ✓ running on port {bridge['port']}")
        print(f"  XMTP:  {bridge.get('address', 'unknown')[:16]}...")
    else:
        print("Bridge:  ✗ not running")


def cmd_bridge(args):
    """Manage the XMTP bridge."""
    from ._internal.bridge import start, stop, check_running, setup_bridge

    if args.action == "start":
        print("Starting XMTP bridge...")
        result = start(COWORKER_DIR, env=args.env or "production")
        if "error" in result:
            print(f"  ✗ {result['error']}")
            if "log" in result and result["log"].strip():
                print(f"\n  Bridge log (last 500 chars):")
                for line in result["log"].strip().split("\n")[-10:]:
                    print(f"    {line}")
            sys.exit(1)
        else:
            print(f"  ✓ Bridge {result['status']} on port {result['port']}")
            xmtp_address = result.get("address", "")
            print(f"  XMTP address: {xmtp_address or 'unknown'}")

            # Sync real XMTP address back to config + wallet
            if xmtp_address:
                _sync_wallet_address(xmtp_address)

    elif args.action == "stop":
        result = stop(COWORKER_DIR)
        print(f"  Bridge: {result['status']}")

    elif args.action == "status":
        result = check_running(COWORKER_DIR)
        if result:
            print(f"  ✓ Running on port {result['port']}")
            print(f"  Address: {result.get('address', 'unknown')}")
        else:
            print("  ✗ Not running")

    elif args.action == "setup":
        try:
            setup_bridge(COWORKER_DIR)
            print("  ✓ Bridge files installed")
        except Exception as e:
            print(f"  ✗ {e}")
            sys.exit(1)


def cmd_invite(args):
    """Generate an invite code for collaborators to connect."""
    config = _load_config()

    # Try to get inbox ID from bridge (preferred — no wallet exposure)
    inbox_id = ""
    try:
        from ._internal.bridge import check_running
        bridge = check_running(COWORKER_DIR)
        if bridge:
            import urllib.request
            port = bridge.get("port", 3500)
            resp = urllib.request.urlopen(f"http://localhost:{port}/inbox-id", timeout=3)
            data = json.loads(resp.read())
            inbox_id = data.get("inboxId", "")
    except Exception:
        pass

    if inbox_id:
        # New format: inbox ID only, no wallet exposed
        invite_data = {"n": config["name"], "i": inbox_id, "v": VERSION}
        short = f"{config['name']}-{inbox_id[:8]}"
    else:
        # Fallback: wallet-based (bridge not running)
        invite_data = {"name": config["name"], "wallet": config["wallet"], "v": VERSION}
        short = f"{config['name']}-{config['wallet'][2:6]}".lower()
        print(f"\n  [note] Bridge not running — invite uses wallet address.")
        print(f"  Start bridge first for privacy-preserving invite: coworker bridge start\n")

    code = base64.b64encode(json.dumps(invite_data, separators=(",", ":")).encode()).decode()

    print(f"\n  Agent:  {config['name']}")
    print(f"\n  ── Share with collaborators ──\n")
    print(f"  Invite code:  {code}")
    print(f"  Short ID:     {short}")
    print(f"\n  Your collaborator runs:")
    print(f"    pip install agent-coworker")
    print(f"    coworker connect {code}")
    print()


def cmd_connect(args):
    """Connect to a peer by invite code or wallet address."""
    target = args.target

    # Route 1: Wallet address (0x...) — legacy/advanced
    if target.startswith("0x") and len(target) >= 40:
        peer_target = target  # wallet address for routing
        peer_wallet = target
        peer_name = args.name or f"peer-{target[2:8]}"
        peer_inbox_id = ""
    else:
        # Route 2: Invite code (base64)
        try:
            decoded = _decode_invite(target)
            peer_name = decoded.get("name") or args.name or "peer"
            peer_inbox_id = decoded.get("inbox_id", "")
            peer_wallet = decoded.get("wallet", "")
            # Prefer inbox ID for routing, fall back to wallet
            peer_target = peer_inbox_id or peer_wallet
            if not peer_target:
                print("  Invalid invite code: no routing info found.")
                print("  The invite code may be from an incompatible version.")
                sys.exit(1)
        except Exception:
            print("  Invalid target. Provide an invite code or wallet address (0x...).")
            sys.exit(1)

    # Save peer
    COWORKER_DIR.mkdir(parents=True, exist_ok=True)
    peers = {}
    if _peers_path().exists():
        try:
            with open(_peers_path()) as f:
                peers = json.load(f)
        except (json.JSONDecodeError, IOError):
            pass

    peer_record = {
        "connected_at": datetime.now(timezone.utc).isoformat(),
    }
    if peer_wallet:
        peer_record["wallet"] = peer_wallet
    if peer_inbox_id:
        peer_record["inbox_id"] = peer_inbox_id

    peers[peer_name] = peer_record

    with open(_peers_path(), "w") as f:
        json.dump(peers, f, indent=2)

    print(f"Connected to: {peer_name}")

    # Try XMTP discover if bridge is running
    from ._internal.bridge import check_running
    bridge = check_running(COWORKER_DIR)
    if bridge:
        print(f"  Discovering skills via XMTP...")
        try:
            from .agent import Agent
            config = _load_config()
            agent = Agent(config.get("name", "cli"), data_dir=str(COWORKER_DIR))
            # Clear stale messages and start poll loop
            import threading
            agent._running = True
            try:
                agent.client.receive(clear=True)
            except Exception:
                pass
            agent._response_box.clear()
            poll = threading.Thread(target=agent._poll_loop, daemon=True)
            poll.start()
            time.sleep(1)  # Let poll thread start consuming

            peer = agent.connect(peer_target, retries=3)
            agent._running = False

            if "error" not in peer:
                skills = peer.get("skills", [])
                skill_names = [s["name"] if isinstance(s, dict) else s for s in skills]
                # Update saved peer with discovered skills + wallet from response
                peers[peer_name]["skills"] = skills
                # If we connected via inbox ID, save the wallet from discovery response
                resp_wallet = peer.get("wallet", "")
                if resp_wallet and not peers[peer_name].get("wallet"):
                    peers[peer_name]["wallet"] = resp_wallet
                with open(_peers_path(), "w") as f:
                    json.dump(peers, f, indent=2)
                print(f"  ✓ Discovered {len(skills)} skills: {', '.join(skill_names)}")
            else:
                print(f"  ⚠ Discovery timed out (peer may be offline)")
                print(f"  Peer saved — skills will be discovered on next connect")
        except Exception as e:
            print(f"  ⚠ Discovery failed: {e}")
            print(f"  Peer saved — try again later")
    else:
        print(f"  ℹ Bridge not running — start with 'coworker bridge start' to discover skills")


def cmd_trust(args):
    """Manage peer trust tiers."""
    from ._internal.security import TrustManager, TrustTier

    config = _load_config()
    tm = TrustManager(str(COWORKER_DIR))

    TIER_NAMES = {"untrusted": 0, "known": 1, "internal": 2, "privileged": 3}

    if args.trust_action == "list":
        tiers = tm.all_tiers
        if not tiers:
            print("No trust overrides set.")
            return
        for wallet, tier_name in tiers.items():
            print(f"  {wallet}  →  {tier_name}")

    elif args.trust_action == "set":
        wallet = args.wallet
        tier_input = args.tier.lower() if args.tier else "known"
        if tier_input in TIER_NAMES:
            tier = TIER_NAMES[tier_input]
        elif tier_input.isdigit() and int(tier_input) in (0, 1, 2, 3):
            tier = int(tier_input)
        else:
            print(f"Invalid tier: {args.tier}")
            print(f"  Valid: untrusted(0), known(1), internal(2), privileged(3)")
            sys.exit(1)
        tm.set_trust_override(wallet, tier)
        label = TrustTier(tier).name.lower()
        print(f"  ✓ {wallet[:16]}... → {label}")

    elif args.trust_action == "remove":
        tm.remove_trust_override(args.wallet)
        print(f"  ✓ Removed trust override for {args.wallet[:16]}...")

    else:
        print("Usage: coworker trust {list|set|remove}")


def cmd_demo(args):
    """Connect to the demo bot and test a skill call."""
    print(f"\n  CoWorker Demo — connect to '{DEMO_BOT_NAME}' and test skills")
    print(f"  {'─' * 50}\n")

    # Check init
    config_path = _config_path()
    if not config_path.exists():
        print("  Not initialized. Run first:")
        print("    coworker init --name my-agent")
        sys.exit(1)

    # Check bridge
    from ._internal.bridge import check_running
    bridge = check_running(COWORKER_DIR)
    if not bridge:
        print("  Bridge not running. Starting...")
        print("    Run: coworker bridge start")
        print("    Then: coworker demo")
        sys.exit(1)

    config = _load_config()
    print(f"  Your agent: {config['name']}")
    print(f"  Demo bot:   {DEMO_BOT_NAME}")
    print(f"  Skills:     {', '.join(DEMO_BOT_SKILLS)}")
    print()

    # Step 1: Connect and discover
    print("  [1/3] Connecting to demo bot...")
    try:
        from .agent import Agent
        agent = Agent(config.get("name", "demo"), data_dir=str(COWORKER_DIR))
        import threading
        agent._running = True
        try:
            agent.client.receive(clear=True)
        except Exception:
            pass
        agent._response_box.clear()
        poll = threading.Thread(target=agent._poll_loop, daemon=True)
        poll.start()
        time.sleep(1)

        peer = agent.connect(_resolve_demo_target(), retries=3)

        if "error" in peer:
            print(f"  ⚠ Could not reach {DEMO_BOT_NAME} — it may be offline.")
            print(f"  Try again later: coworker demo")
            agent._running = False
            sys.exit(1)

        skills = peer.get("skills", [])
        skill_names = [s["name"] if isinstance(s, dict) else s for s in skills]
        print(f"  ✓ Connected! Found {len(skills)} skills: {', '.join(skill_names)}")

        # Save peer
        peers = {}
        if _peers_path().exists():
            try:
                with open(_peers_path()) as f:
                    peers = json.load(f)
            except (json.JSONDecodeError, IOError):
                pass
        peers[DEMO_BOT_NAME] = {
            "wallet": _resolve_demo_target(),
            "skills": skills,
            "connected_at": datetime.now(timezone.utc).isoformat(),
        }
        with open(_peers_path(), "w") as f:
            json.dump(peers, f, indent=2)

    except Exception as e:
        print(f"  ✗ Connection failed: {e}")
        sys.exit(1)

    # Step 2: Call about — let icy introduce CoWorker
    print(f"\n  [2/4] Calling {DEMO_BOT_NAME}.about('general')...")
    print(f"        (You're calling a remote skill via XMTP — E2E encrypted)")
    try:
        # First call after discover is often slow (XMTP conversation setup ~30-60s)
        print(f"        (First call may take 30-60s for XMTP conversation setup)")
        result = agent.call(_resolve_demo_target(), "about", {"topic": "general"}, timeout=60, retries=2)
        if "error" not in result:
            data = result.get("result", result)
            print(f"\n  icy says:")
            answer = data.get("answer", str(data))
            # Wrap text for readability
            words = answer.split()
            line = "    "
            for w in words:
                if len(line) + len(w) > 72:
                    print(line)
                    line = "    " + w
                else:
                    line += " " + w if line.strip() else w
            if line.strip():
                print(line)
        else:
            print(f"  ⚠ about() failed: {result.get('error', 'timeout')}")
    except Exception as e:
        print(f"  ⚠ about() failed: {e}")

    # Step 3: Call translate — show a practical skill
    print(f"\n  [3/4] Calling {DEMO_BOT_NAME}.translate('Hello world', to_lang='zh')...")
    print(f"        (icy's translate code is private — you only see input/output)")
    try:
        result = agent.call(_resolve_demo_target(), "translate", {
            "text": "Hello world", "to_lang": "zh"
        }, timeout=45, retries=2)
        if "error" not in result:
            data = result.get("result", result)
            print(f"  ✓ {json.dumps(data, ensure_ascii=False)}")
        else:
            print(f"  ⚠ translate() failed: {result.get('error', 'timeout')}")
    except Exception as e:
        print(f"  ⚠ translate() failed: {e}")

    # Step 4: Call search — show trust-gated skill
    print(f"\n  [4/4] Calling {DEMO_BOT_NAME}.search('coworker protocol')...")
    print(f"        (This skill requires KNOWN trust — you were auto-granted)")
    try:
        result = agent.call(_resolve_demo_target(), "search", {"query": "coworker protocol"}, timeout=45, retries=2)
        if "error" not in result:
            data = result.get("result", result)
            results_list = data.get("results", [])
            for r in results_list:
                print(f"    • {r}")
        else:
            print(f"  ⚠ search() failed: {result.get('error', 'timeout')}")
    except Exception as e:
        print(f"  ⚠ search() failed: {e}")

    agent._running = False

    print(f"\n  {'─' * 50}")
    print(f"  Demo complete! What just happened:")
    print(f"    ✓ Connected to icy across the internet (XMTP)")
    print(f"    ✓ Discovered skills without seeing icy's code")
    print(f"    ✓ Called 3 remote skills — E2E encrypted")
    print(f"    ✓ Trust was checked before each call")
    print()
    print(f"  Now try it yourself:")
    print(f"    1. python bot.py              Start your own agent")
    print(f"    2. coworker invite             Share your invite code")
    print(f"    3. Your friend runs:           coworker connect <code>")
    print(f"    4. They call your skills — without seeing your code!")
    print()


def cmd_skills(args):
    """Manage skill visibility — control which skills peers can discover."""
    from agent_coworker._internal.skill_visibility import (
        SkillVisibilityConfig, STATE_EXPOSED, STATE_HIDDEN,
    )

    config = SkillVisibilityConfig(str(COWORKER_DIR))
    config.load()
    action = getattr(args, "skills_action", None)

    if action == "list" or action is None:
        skills = config.get_skills()
        if not skills:
            print("  No skill visibility config found.")
            print("  Skills are configured when you first run agent.serve().")
            print("  Or use: coworker skills configure --expose skill1,skill2")
            return
        print()
        for name, cfg in sorted(skills.items()):
            state = cfg.get("state", "hidden")
            marker = "✓" if state == "exposed" else "✗"
            pending = " (new, pending review)" if cfg.get("pending_review") else ""
            tier = ""
            label = "Exposed" if state == "exposed" else "Hidden"
            print(f"  {marker} {name:<20s} {label}{pending}")
        total = len(skills)
        exposed = sum(1 for c in skills.values() if c.get("state") == "exposed")
        print(f"\n  {exposed}/{total} skills exposed to peers.")

    elif action == "configure":
        skills = config.get_skills()
        if not skills:
            print("  No skills registered yet. Run your bot first, then configure.")
            return

        # Handle non-interactive flags
        if args.all_expose:
            for name in skills:
                config.set_state(name, STATE_EXPOSED)
            config.save()
            print(f"  ✓ All {len(skills)} skills exposed.")
            return
        if args.all_hide:
            for name in skills:
                config.set_state(name, STATE_HIDDEN)
            config.save()
            print(f"  ✓ All {len(skills)} skills hidden.")
            return
        if args.expose:
            for name in args.expose.split(","):
                name = name.strip()
                if name in skills:
                    config.set_state(name, STATE_EXPOSED)
                else:
                    print(f"  ⚠ Unknown skill: {name}")
            config.save()
            print(f"  ✓ Updated.")
            return
        if args.hide:
            for name in args.hide.split(","):
                name = name.strip()
                if name in skills:
                    config.set_state(name, STATE_HIDDEN)
                else:
                    print(f"  ⚠ Unknown skill: {name}")
            config.save()
            print(f"  ✓ Updated.")
            return

        # Interactive mode
        items = sorted(skills.items())
        print(f"\n  ── Skill Visibility Configure {'─' * 28}")
        print(f"  Toggle skills by entering their number. Type 'done' to save.\n")
        while True:
            for i, (name, cfg) in enumerate(items, 1):
                state = cfg.get("state", "hidden")
                marker = "✓" if state == "exposed" else "✗"
                pending = " (pending review)" if cfg.get("pending_review") else ""
                print(f"    [{i}] {marker} {name}{pending}")
            print()
            try:
                choice = input("  Toggle (number) or 'done': ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                print("\n  Cancelled.")
                return
            if choice in ("done", "d", ""):
                break
            try:
                idx = int(choice) - 1
                if 0 <= idx < len(items):
                    name = items[idx][0]
                    current = skills[name].get("state", "hidden")
                    new_state = STATE_HIDDEN if current == "exposed" else STATE_EXPOSED
                    config.set_state(name, new_state)
                    skills[name]["state"] = new_state
                    print(f"  → {name}: {'Exposed' if new_state == 'exposed' else 'Hidden'}\n")
                else:
                    print(f"  Invalid number.\n")
            except ValueError:
                print(f"  Enter a number or 'done'.\n")

        if config.save():
            exposed = sum(1 for c in skills.values() if c.get("state") == "exposed")
            print(f"\n  ✓ Saved. {exposed}/{len(skills)} skills exposed.")
        else:
            print(f"\n  ⚠ Failed to save config.")

    elif action == "expose":
        name = args.skill_name
        if not config.get_skills().get(name):
            print(f"  ⚠ Unknown skill: {name}")
            return
        config.set_state(name, STATE_EXPOSED)
        if config.save():
            print(f"  ✓ {name}: Exposed")
        else:
            print(f"  ⚠ Failed to save.")

    elif action == "hide":
        name = args.skill_name
        if not config.get_skills().get(name):
            print(f"  ⚠ Unknown skill: {name}")
            return
        config.set_state(name, STATE_HIDDEN)
        if config.save():
            print(f"  ✓ {name}: Hidden")
        else:
            print(f"  ⚠ Failed to save.")

    elif action == "preview":
        tier_map = {"untrusted": 0, "known": 1, "internal": 2, "privileged": 3}
        tier_str = args.peer_tier.lower()
        peer_tier = tier_map.get(tier_str)
        if peer_tier is None:
            try:
                peer_tier = int(tier_str)
            except ValueError:
                print(f"  ⚠ Invalid tier: {args.peer_tier}")
                print(f"  Valid: untrusted/known/internal/privileged or 0-3")
                return

        skills_cfg = config.get_skills()
        exposed = config.get_exposed_set()
        # Simulate what a peer at this tier would see
        visible = []
        for name in sorted(exposed):
            cfg = skills_cfg.get(name, {})
            # We don't have skill_def here, so show all exposed skills
            # and note the min_trust_tier info if available
            visible.append(name)

        tier_name = {0: "UNTRUSTED", 1: "KNOWN", 2: "INTERNAL", 3: "PRIVILEGED"}.get(peer_tier, str(peer_tier))
        print(f"\n  Peer tier: {tier_name}\n")
        if visible:
            print(f"  Visible skills:")
            for name in visible:
                print(f"    - {name}")
        else:
            print(f"  No skills visible at this tier.")
        print(f"\n  Note: This preview shows skills from persistent config.")
        print(f"  Runtime overrides (serve(expose_skills=...)) are not reflected.")

    elif action == "reset":
        config.reset()
        print(f"  ✓ Skill visibility config removed.")
        print(f"  Next serve() will run the first-time guide.")


def cmd_request(args):
    """Send an async task request to a peer."""
    import threading
    from agent_coworker.agent import Agent

    agent = Agent("cli-caller", data_dir=str(COWORKER_DIR))
    agent._running = True

    # Start poll loop to receive responses
    poll = threading.Thread(target=agent._poll_loop, daemon=True)
    poll.start()
    time.sleep(1)

    target = args.target
    skill = args.skill
    input_str = args.input or "{}"

    try:
        input_data = json.loads(input_str)
    except json.JSONDecodeError:
        print(f"  ✗ Invalid JSON input: {input_str}")
        sys.exit(1)

    # Decode invite if needed
    target_addr = _resolve_target(target)

    task_id = agent.request(target_addr, skill, input_data)
    print(f"\n  Task queued: {task_id[:8]}...")
    print(f"  Check status: coworker tasks")
    print(f"  Get result:   coworker result {task_id[:8]}")
    agent._running = False


def cmd_tasks(args):
    """List async tasks."""
    from agent_coworker._internal.task_queue import AsyncTaskQueue, ACTIVE_STATES

    queue = AsyncTaskQueue(str(COWORKER_DIR))
    state_filter = getattr(args, 'state', None)
    tasks = queue.list_tasks(state=state_filter, limit=30)

    if not tasks:
        print("  No async tasks found.")
        print("  Send one: coworker request <invite> <skill> --input '{}'")
        return

    # Expire check
    queue.cleanup_expired()
    tasks = queue.list_tasks(state=state_filter, limit=30)

    print()
    for t in tasks:
        state = t.state
        if state == "succeeded":
            marker = "✓"
            color = ""
        elif state == "failed":
            marker = "✗"
            color = ""
        elif state == "expired":
            marker = "⏰"
            color = ""
        else:
            marker = "…"
            color = ""

        print(f"  {marker} {t.task_id[:8]}  {t.skill:<16s}  → {t.peer_name:<16s}  {state}")

    active = sum(1 for t in tasks if t.state in ACTIVE_STATES)
    done = sum(1 for t in tasks if t.state == "succeeded")
    print(f"\n  {len(tasks)} tasks ({active} pending, {done} completed)")


def cmd_result(args):
    """Get result of an async task."""
    from agent_coworker._internal.task_queue import AsyncTaskQueue

    queue = AsyncTaskQueue(str(COWORKER_DIR))
    task_id = args.task_id

    # Support short IDs (prefix match)
    if len(task_id) < 32:
        tasks = queue.list_tasks(limit=500)
        matches = [t for t in tasks if t.task_id.startswith(task_id)]
        if len(matches) == 0:
            print(f"  ✗ No task matching '{task_id}'")
            return
        if len(matches) > 1:
            print(f"  ✗ Ambiguous ID '{task_id}', matches {len(matches)} tasks:")
            for m in matches[:5]:
                print(f"    {m.task_id[:12]} ({m.skill})")
            return
        task_id = matches[0].task_id

    task = queue.load(task_id)
    if task is None:
        print(f"  ✗ Task not found: {task_id}")
        return

    print(f"\n  Task:    {task.task_id[:8]}...")
    print(f"  Skill:   {task.skill}")
    print(f"  Peer:    {task.peer_name}")
    print(f"  State:   {task.state}")
    print(f"  Created: {task.created_at}")

    if task.state == "succeeded" and task.result:
        if args.json:
            print(json.dumps(task.result, ensure_ascii=False, indent=2))
        else:
            print(f"\n  Result:")
            print(f"  {json.dumps(task.result, ensure_ascii=False, indent=2)}")
    elif task.error:
        print(f"\n  Error: {task.error}")
    elif task.state in ("queued", "accepted", "running"):
        print(f"\n  Status: waiting for peer to process...")
        if not args.json:
            print(f"  Polling for response (30s)...")
            # Auto-poll: start a temporary agent to receive responses
            import threading
            try:
                from agent_coworker.agent import Agent
                agent = Agent("cli-poll", data_dir=str(COWORKER_DIR))
                agent._running = True
                poll = threading.Thread(target=agent._poll_loop, daemon=True)
                poll.start()
                for _ in range(15):
                    time.sleep(2)
                    task = queue.load(task_id)
                    if task and task.state in ("succeeded", "failed", "expired"):
                        break
                agent._running = False
                # Re-display result if completed
                if task and task.state == "succeeded" and task.result:
                    print(f"\n  ✓ Completed!")
                    print(f"  {json.dumps(task.result, ensure_ascii=False, indent=2)}")
                elif task and task.state == "failed":
                    print(f"\n  ✗ Failed: {task.error}")
                else:
                    print(f"\n  Still pending. Run 'coworker result {task_id[:8]}' again later.")
            except Exception as e:
                print(f"\n  Could not poll: {e}")
                print(f"  Run 'coworker result {task_id[:8]}' again later.")


def _resolve_target(target: str) -> str:
    """Resolve invite code or raw address to inbox/wallet address."""
    if target.startswith("eyJ"):
        data = json.loads(base64.b64decode(target))
        return data.get("i", data.get("wallet", target))
    return target


def cmd_version(args):
    """Print version."""
    print(f"agent-coworker {VERSION}")


# ── Main ──────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        prog="coworker",
        description="agent-coworker — peer-to-peer AI agent collaboration over XMTP",
        epilog="""examples:
  coworker init --name my-bot        Create agent identity + install XMTP bridge
  coworker bridge start              Start XMTP networking (E2E encrypted)
  coworker invite                    Generate shareable invite code
  coworker connect <invite-code>     Connect to a collaborator's agent
  coworker trust set 0xPEER known    Grant 'known' trust to a peer
  coworker status                    Check agent & bridge status

quick start:
  1. coworker init --name my-bot     Initialize
  2. coworker bridge start           Start XMTP networking
  3. coworker demo                   Connect to demo bot & test skills

full workflow:
  1. Write bot.py with @agent.skill  Define your skills
  2. python bot.py                   Start agent (XMTP + dashboard)
  3. coworker invite                 Share invite code
  4. Collaborator: coworker connect  Auto-discover & collaborate

docs: https://github.com/ZiwayZhao/agent-coworker""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command")

    # init
    p_init = sub.add_parser("init",
        help="Initialize agent identity and XMTP bridge",
        description="""Create a new agent identity (wallet + config) and install the XMTP bridge.

This generates:
  ~/.coworker/config.json   Agent name + wallet address
  ~/.coworker/wallet.json   Private key (never shared)
  ~/.coworker/bridge/       XMTP bridge (Node.js)

Requires Node.js >= 22 for XMTP networking.""",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p_init.add_argument("--name", default=None, help="Agent name (default: 'agent')")
    p_init.add_argument("--force", action="store_true", help="Force re-initialization (overwrites existing config)")

    # status
    sub.add_parser("status",
        help="Show agent status, peers, and bridge info",
        description="""Display current agent identity, connected peers count,
and XMTP bridge status (running/stopped, port, address).""")

    # bridge
    p_bridge = sub.add_parser("bridge",
        help="Manage XMTP bridge (start/stop/status/setup)",
        description="""The XMTP bridge is a Node.js process that connects your agent
to the XMTP network for E2E encrypted, cross-network messaging.

actions:
  start    Start the bridge process (listens on localhost)
  stop     Stop the bridge process
  status   Check if bridge is running
  setup    Re-install bridge dependencies (npm install)

The bridge auto-starts when you call agent.serve(). Use this
command for manual control or troubleshooting.""",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p_bridge.add_argument("action", choices=["start", "stop", "status", "setup"],
                          help="Bridge action")
    p_bridge.add_argument("--env", default="production", choices=["dev", "production"],
                          help="XMTP environment (default: production)")

    # invite
    sub.add_parser("invite",
        help="Generate invite code for collaborators",
        description="""Generate a shareable invite code that others can use to connect.

The invite code is a base64-encoded JSON containing your agent name
and wallet address. Share it via chat, email, or any channel.

Your collaborator runs:
  coworker connect <invite-code>

No wallet address needed — the code contains everything.""")

    # connect
    p_connect = sub.add_parser("connect",
        help="Connect to a peer agent by invite code or wallet",
        description="""Connect to another agent using their invite code or wallet address.

examples:
  coworker connect eyJuYW1lIjoi...   Connect via invite code
  coworker connect 0xAbCd...1234     Connect via wallet address

If the XMTP bridge is running, skills are auto-discovered.
Otherwise, the peer is saved and discovery happens on next connect.""",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p_connect.add_argument("target", help="Invite code (base64) or wallet address (0x...)")
    p_connect.add_argument("--name", default=None, help="Custom name for this peer")

    # trust
    p_trust = sub.add_parser("trust",
        help="Manage peer trust tiers (controls skill visibility)",
        description="""Control which skills each peer can see and call.

trust tiers:
  untrusted (0)   Can ping only, sees NO skills (default for new peers)
  known (1)       Can see and call skills marked min_trust_tier=1
  internal (2)    Can query context, deep collaboration
  privileged (3)  Full access to all skills — grant carefully

Trust auto-downgrades after OKR completion:
  PRIVILEGED → INTERNAL → KNOWN (never below KNOWN)

examples:
  coworker trust list                     Show all trust overrides
  coworker trust set 0xPEER known         Grant 'known' access
  coworker trust set 0xPEER privileged    Grant full access
  coworker trust remove 0xPEER            Reset to default (untrusted)""",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    trust_sub = p_trust.add_subparsers(dest="trust_action")
    trust_sub.add_parser("list", help="List all trust overrides")
    p_trust_set = trust_sub.add_parser("set", help="Set trust tier for a peer")
    p_trust_set.add_argument("wallet", help="Peer wallet address (0x...)")
    p_trust_set.add_argument("tier", help="Trust tier: untrusted/known/internal/privileged or 0-3")
    p_trust_rm = trust_sub.add_parser("remove", help="Remove trust override")
    p_trust_rm.add_argument("wallet", help="Peer wallet address (0x...)")

    # skills
    p_skills = sub.add_parser("skills",
        help="Manage skill visibility (control what peers can discover)",
        description="""Control which of your agent's skills are visible to peers.

Skills registered via @agent.skill() are managed through a visibility policy.
By default, all skills are hidden until you review them on first serve().

commands:
  list          Show current skill visibility (default)
  configure     Interactive configuration
  expose NAME   Expose a specific skill
  hide NAME     Hide a specific skill
  preview       Preview what a peer would see
  reset         Remove visibility config

examples:
  coworker skills                           List all skills and visibility
  coworker skills configure                 Interactive toggle
  coworker skills configure --all-expose    Expose everything
  coworker skills expose search             Expose 'search' skill
  coworker skills hide admin                Hide 'admin' skill
  coworker skills preview --peer-tier known Preview KNOWN peer's view
  coworker skills reset                     Reset (re-run first-time guide)""",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    skills_sub = p_skills.add_subparsers(dest="skills_action")
    skills_sub.add_parser("list", help="List skills and their visibility state")
    p_skills_cfg = skills_sub.add_parser("configure", help="Configure skill visibility")
    p_skills_cfg.add_argument("--expose", default=None, help="Comma-separated skills to expose")
    p_skills_cfg.add_argument("--hide", default=None, help="Comma-separated skills to hide")
    p_skills_cfg.add_argument("--all-expose", action="store_true", help="Expose all skills")
    p_skills_cfg.add_argument("--all-hide", action="store_true", help="Hide all skills")
    p_skills_expose = skills_sub.add_parser("expose", help="Expose a specific skill")
    p_skills_expose.add_argument("skill_name", help="Skill name to expose")
    p_skills_hide = skills_sub.add_parser("hide", help="Hide a specific skill")
    p_skills_hide.add_argument("skill_name", help="Skill name to hide")
    p_skills_preview = skills_sub.add_parser("preview", help="Preview peer-visible skills")
    p_skills_preview.add_argument("--peer-tier", required=True,
                                   help="Peer trust tier: untrusted/known/internal/privileged or 0-3")
    skills_sub.add_parser("reset", help="Reset visibility config")

    # request (async)
    p_request = sub.add_parser("request",
        help="Send an async task request (peer can be offline)",
        description="""Send a task request to a peer agent. Unlike 'call', this returns
immediately — the request is queued via XMTP. When the peer comes
online, their agent processes it and the result is stored locally.

examples:
  coworker request eyJu... translate --input '{"text":"hello","lang":"zh"}'
  coworker request eyJu... analyze --input '{"data":"quarterly report"}'

Check results:
  coworker tasks              List all async tasks
  coworker result <task-id>   Get result of a specific task""",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p_request.add_argument("target", help="Invite code (base64) or inbox ID")
    p_request.add_argument("skill", help="Skill name to call")
    p_request.add_argument("--input", default="{}", help="JSON input (default: {})")

    # tasks
    p_tasks = sub.add_parser("tasks",
        help="List async task requests and their status",
        description="Show all async tasks: pending, completed, failed, expired.")
    p_tasks.add_argument("--state", default=None, help="Filter by state: queued/succeeded/failed/expired")

    # result
    p_result = sub.add_parser("result",
        help="Get result of an async task",
        description="Get the result of a completed async task by task ID (supports short IDs).")
    p_result.add_argument("task_id", help="Task ID (full or prefix)")
    p_result.add_argument("--json", action="store_true", help="Output raw JSON only")

    # demo
    sub.add_parser("demo",
        help="Connect to the demo bot and test skills",
        description=f"""Connect to '{DEMO_BOT_NAME}', the official demo bot, and test skill calls.

This is the fastest way to experience CoWorker. The demo bot is always
online and has these skills:
  ping       — Check if agent is alive
  translate  — Translate text between languages
  search     — Search the web for information

The demo will:
  1. Connect to {DEMO_BOT_NAME} via XMTP (auto-discover skills)
  2. Call ping() to verify connectivity
  3. Call translate('Hello world', to_lang='zh')

Requires: coworker init + coworker bridge start""",
        formatter_class=argparse.RawDescriptionHelpFormatter)

    # version
    sub.add_parser("version", help="Print version")

    args = parser.parse_args()

    commands = {
        "init": cmd_init,
        "status": cmd_status,
        "bridge": cmd_bridge,
        "invite": cmd_invite,
        "connect": cmd_connect,
        "request": cmd_request,
        "tasks": cmd_tasks,
        "result": cmd_result,
        "trust": cmd_trust,
        "skills": cmd_skills,
        "demo": cmd_demo,
        "version": cmd_version,
    }

    if args.command in commands:
        commands[args.command](args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
