"""Async Task Queue — local persistence for async request/response.

State machine:
  queued → accepted → running → succeeded
                              → failed
                              → expired (TTL)

Tasks are stored as individual JSON files in data_dir/async_tasks/.
task_id is generated by the sender (idempotency key).
"""

import json
import logging
import os
import tempfile
import time
from datetime import datetime, timezone
from typing import Dict, List, Optional

logger = logging.getLogger("coworker.task_queue")

# Task states
QUEUED = "queued"
ACCEPTED = "accepted"
RUNNING = "running"
SUCCEEDED = "succeeded"
FAILED = "failed"
EXPIRED = "expired"

TERMINAL_STATES = {SUCCEEDED, FAILED, EXPIRED}
ACTIVE_STATES = {QUEUED, ACCEPTED, RUNNING}

DEFAULT_TTL_SECONDS = 7 * 24 * 3600  # 7 days


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _now_ts() -> float:
    return time.time()


class AsyncTask:
    """A single async task record."""

    __slots__ = (
        "task_id", "peer_inbox", "peer_name", "skill", "input_data",
        "state", "result", "error", "created_at", "updated_at",
        "ttl_seconds", "correlation_id",
    )

    def __init__(self, task_id: str, peer_inbox: str, skill: str,
                 input_data: dict, peer_name: str = "",
                 ttl_seconds: int = DEFAULT_TTL_SECONDS,
                 correlation_id: str = ""):
        self.task_id = task_id
        self.peer_inbox = peer_inbox
        self.peer_name = peer_name or peer_inbox[:12] + "..."
        self.skill = skill
        self.input_data = input_data
        self.state = QUEUED
        self.result: Optional[dict] = None
        self.error: Optional[str] = None
        self.created_at = _now_iso()
        self.updated_at = self.created_at
        self.ttl_seconds = ttl_seconds
        self.correlation_id = correlation_id

    def is_expired(self) -> bool:
        try:
            created = datetime.fromisoformat(self.created_at)
            elapsed = (datetime.now(timezone.utc) - created).total_seconds()
            return elapsed > self.ttl_seconds
        except (ValueError, TypeError):
            return False

    def to_dict(self) -> dict:
        return {
            "task_id": self.task_id,
            "peer_inbox": self.peer_inbox,
            "peer_name": self.peer_name,
            "skill": self.skill,
            "input_data": self.input_data,
            "state": self.state,
            "result": self.result,
            "error": self.error,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "ttl_seconds": self.ttl_seconds,
            "correlation_id": self.correlation_id,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "AsyncTask":
        t = cls(
            task_id=d["task_id"],
            peer_inbox=d["peer_inbox"],
            skill=d["skill"],
            input_data=d.get("input_data", {}),
            peer_name=d.get("peer_name", ""),
            ttl_seconds=d.get("ttl_seconds", DEFAULT_TTL_SECONDS),
            correlation_id=d.get("correlation_id", ""),
        )
        t.state = d.get("state", QUEUED)
        t.result = d.get("result")
        t.error = d.get("error")
        t.created_at = d.get("created_at", _now_iso())
        t.updated_at = d.get("updated_at", t.created_at)
        return t


class AsyncTaskQueue:
    """Persistent async task queue backed by JSON files.

    Storage: data_dir/async_tasks/{task_id}.json
    One file per task. No database needed.
    """

    def __init__(self, data_dir: str):
        self._dir = os.path.join(data_dir, "async_tasks")
        os.makedirs(self._dir, exist_ok=True)

    def _task_path(self, task_id: str) -> str:
        """Sanitize task_id for filesystem. Uses hex encoding to avoid collisions."""
        if not task_id:
            raise ValueError("task_id cannot be empty")
        # Use the task_id directly if it's a valid UUID format, otherwise hex-encode
        safe_id = "".join(c for c in task_id if c.isalnum() or c == "-")
        if not safe_id:
            # Fallback: hex-encode the original string
            safe_id = task_id.encode().hex()
        return os.path.join(self._dir, f"{safe_id}.json")

    def save(self, task: AsyncTask) -> bool:
        """Atomically save task to disk with restricted permissions."""
        task.updated_at = _now_iso()
        path = self._task_path(task.task_id)
        fd = None
        tmp_path = None
        try:
            fd, tmp_path = tempfile.mkstemp(dir=self._dir, suffix=".tmp")
            with os.fdopen(fd, "w") as f:
                fd = None  # os.fdopen takes ownership
                json.dump(task.to_dict(), f, indent=2, ensure_ascii=False)
                f.flush()
                os.fsync(f.fileno())
            # Restrict to owner-only
            os.chmod(tmp_path, 0o600)
            os.replace(tmp_path, path)
            return True
        except (IOError, OSError) as e:
            logger.error("Failed to save task %s: %s", task.task_id, e)
            if fd is not None:
                os.close(fd)
            if tmp_path:
                try:
                    os.unlink(tmp_path)
                except OSError:
                    pass
            return False

    def load(self, task_id: str) -> Optional[AsyncTask]:
        """Load a task by ID."""
        path = self._task_path(task_id)
        if not os.path.isfile(path):
            return None
        try:
            with open(path) as f:
                data = json.load(f)
            task = AsyncTask.from_dict(data)
            # Check expiry
            if task.state in ACTIVE_STATES and task.is_expired():
                task.state = EXPIRED
                task.error = f"TTL expired ({task.ttl_seconds}s)"
                self.save(task)
            return task
        except (json.JSONDecodeError, IOError, KeyError) as e:
            logger.error("Failed to load task %s: %s", task_id, e)
            return None

    def exists(self, task_id: str) -> bool:
        """Check if task exists (idempotency)."""
        return os.path.isfile(self._task_path(task_id))

    def list_tasks(self, state: Optional[str] = None,
                   limit: int = 50) -> List[AsyncTask]:
        """List tasks, optionally filtered by state. Most recent first."""
        tasks = []
        try:
            files = sorted(os.listdir(self._dir), reverse=True)
        except OSError:
            return []

        for fname in files:
            if not fname.endswith(".json"):
                continue
            task_id = fname[:-5]
            task = self.load(task_id)
            if task is None:
                continue
            if state and task.state != state:
                continue
            tasks.append(task)
            if len(tasks) >= limit:
                break
        return tasks

    def complete(self, task_id: str, result: dict) -> bool:
        """Mark task as succeeded with result."""
        task = self.load(task_id)
        if task is None:
            logger.warning("Cannot complete unknown task: %s", task_id)
            return False
        if task.state in TERMINAL_STATES:
            logger.warning("Task %s already in terminal state: %s", task_id, task.state)
            return False
        task.state = SUCCEEDED
        task.result = result
        return self.save(task)

    def fail(self, task_id: str, error: str) -> bool:
        """Mark task as failed."""
        task = self.load(task_id)
        if task is None:
            return False
        if task.state in TERMINAL_STATES:
            return False
        task.state = FAILED
        task.error = error
        return self.save(task)

    def cleanup_expired(self) -> int:
        """Check all active tasks and expire those past TTL. Returns count."""
        expired_count = 0
        for task in self.list_tasks(limit=500):
            if task.state in ACTIVE_STATES and task.is_expired():
                task.state = EXPIRED
                task.error = f"TTL expired ({task.ttl_seconds}s)"
                self.save(task)
                expired_count += 1
        return expired_count

    def find_by_correlation(self, correlation_id: str) -> Optional[AsyncTask]:
        """Find a task by its correlation_id (for matching responses)."""
        for task in self.list_tasks(limit=500):
            if task.correlation_id == correlation_id:
                return task
        return None
